name: seniorcare
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

# Versioning
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8 # Updated to the latest
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.1.2 # Updated to the latest
  firebase_core: ^3.1.1 # Updated to the latest
  firebase_auth: ^5.1.1 # Updated to the latest
  cloud_firestore: ^5.0.2 # Updated to the latest
  cloud_functions: ^5.0.3
  firebase_storage: ^12.1.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  mailer: ^6.1.1
  flutter_email_sender: ^6.0.3
  http: ^0.13.3
  audioplayers: ^6.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.0.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_webservice: ^0.0.19
  agora_rtc_engine: ^6.3.2
  firebase_messaging: ^15.0.2
  flutter_map: ^4.0.0
  flutter_typeahead: ^5.0.0
  latlong2: ^0.8.1
  permission_handler: ^11.3.1
  
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to the latest

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/ring.mp3