name: seniorcare
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

# Versioning
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8 # Updated to the latest
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.1.2 # Updated to the latest
  firebase_core: ^3.1.1 # Updated to the latest
  firebase_auth: ^5.1.1 # Updated to the latest
  cloud_firestore: ^5.0.2 # Updated to the latest
  firebase_storage: ^12.1.0
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to the latest

flutter:
  uses-material-design: true
  assets:
    - assets/images/
