// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLUdmY-5AdIye5DIxGyjITHszicQuw9o',
    appId: '1:960760282678:web:f3a351c4e5071ef1cfe297',
    messagingSenderId: '960760282678',
    projectId: 'seniorcare-17d1f',
    authDomain: 'seniorcare-17d1f.firebaseapp.com',
    storageBucket: 'seniorcare-17d1f.appspot.com',
    measurementId: 'G-XL62PSCFXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyWNuF4SN5HUEFC0Ju_hs-q-H-il3gIg8',
    appId: '1:960760282678:android:d01af368525bb8b2cfe297',
    messagingSenderId: '960760282678',
    projectId: 'seniorcare-17d1f',
    storageBucket: 'seniorcare-17d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOFyH5Ofdeps_iXqxW9EcB-GPC4CYZrUE',
    appId: '1:960760282678:ios:dea9c7ee1a2340c2cfe297',
    messagingSenderId: '960760282678',
    projectId: 'seniorcare-17d1f',
    storageBucket: 'seniorcare-17d1f.appspot.com',
    iosBundleId: 'com.example.seniorcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOFyH5Ofdeps_iXqxW9EcB-GPC4CYZrUE',
    appId: '1:960760282678:ios:dea9c7ee1a2340c2cfe297',
    messagingSenderId: '960760282678',
    projectId: 'seniorcare-17d1f',
    storageBucket: 'seniorcare-17d1f.appspot.com',
    iosBundleId: 'com.example.seniorcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLUdmY-5AdIye5DIxGyjITHszicQuw9o',
    appId: '1:960760282678:web:23bf6335efbb88fdcfe297',
    messagingSenderId: '960760282678',
    projectId: 'seniorcare-17d1f',
    authDomain: 'seniorcare-17d1f.firebaseapp.com',
    storageBucket: 'seniorcare-17d1f.appspot.com',
    measurementId: 'G-SY049JWQM8',
  );
}
